# Generated by Django 5.1.6 on 2025-03-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ruta_plano',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
