# Generated by Django 5.1.6 on 2025-03-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_fecha_creacion_pedido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='ruta_plano',
        ),
        migrations.AddField(
            model_name='pedido',
            name='plano',
            field=models.ImageField(blank=True, null=True, upload_to='planos/'),
        ),
    ]
