# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1277, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidePanel = QtWidgets.QWidget(self.centralwidget)
        self.sidePanel.setGeometry(QtCore.QRect(1, 1, 221, 721))
        self.sidePanel.setAutoFillBackground(False)
        self.sidePanel.setStyleSheet("background-color: #ffffff;\n"
"")
        self.sidePanel.setObjectName("sidePanel")
        self.label_9 = QtWidgets.QLabel(self.sidePanel)
        self.label_9.setGeometry(QtCore.QRect(60, 20, 81, 81))
        self.label_9.setStyleSheet("")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("imagenes/profile_6063734.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.sidePanel)
        self.label_10.setGeometry(QtCore.QRect(213, 303, 861, 861))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setStyleSheet("")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(".imagenes/klipartz.com.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.home = QtWidgets.QPushButton(self.sidePanel)
        self.home.setGeometry(QtCore.QRect(70, 170, 81, 31))
        self.home.setStyleSheet("\n"
"font-family: \"Roboto\";\n"
"    font-weight: 900; /* Semibold */\n"
"    font-size: 16px;\n"
"    color: #333333; /* Color de texto */;\n"
"border:none")
        self.home.setObjectName("home")
        self.label_11 = QtWidgets.QLabel(self.sidePanel)
        self.label_11.setGeometry(QtCore.QRect(20, 160, 51, 51))
        self.label_11.setStyleSheet("")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("imagenes/klipartz.com.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.topPanel = QtWidgets.QFrame(self.centralwidget)
        self.topPanel.setGeometry(QtCore.QRect(210, 0, 1071, 81))
        self.topPanel.setStyleSheet("background-color: #ffffff;\n"
"")
        self.topPanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topPanel.setObjectName("topPanel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topPanel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Cliente = QtWidgets.QLineEdit(self.topPanel)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(99)
        self.Cliente.setFont(font)
        self.Cliente.setStyleSheet("    font-family: \"Roboto\";\n"
"    font-weight: 900; /* Semibold */\n"
"    font-size: 24px;\n"
"    color: #333333; /* Color de texto */\n"
" border: none;")
        self.Cliente.setAlignment(QtCore.Qt.AlignLeft)
        self.Cliente.setObjectName("Cliente")
        self.horizontalLayout.addWidget(self.Cliente)
        self.horizontalLayout.addStretch()
        self.btnNuevoPedido = QtWidgets.QPushButton(self.topPanel)
        self.btnNuevoPedido.setStyleSheet("""
            QPushButton {
                background-color: #28a745;
                color: white;
                font-family: "Roboto";
                font-weight: bold;
                font-size: 16px;
                padding: 8px 16px;
                border-radius: 5px;
                border: none;
                cursor: pointer;
                transition: background-color 0.3s ease;
            }
            QPushButton:hover {
                background-color: #218838;
            }
            QPushButton:pressed {
                background-color: #1e7e34;
            }
        """)
        self.btnNuevoPedido.setObjectName("btnNuevoPedido")
        self.horizontalLayout.addWidget(self.btnNuevoPedido)
        self.pantallaHome = QtWidgets.QFrame(self.centralwidget)
        self.pantallaHome.setGeometry(QtCore.QRect(220, 80, 1061, 641))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pantallaHome.sizePolicy().hasHeightForWidth())
        self.pantallaHome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pantallaHome.setFont(font)
        self.pantallaHome.setStyleSheet("background-color: #1697D1;\n"
"")
        self.pantallaHome.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pantallaHome.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pantallaHome.setObjectName("pantallaHome")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.pantallaHome)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 1061, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(30)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    border-top-left-radius: 30px;\n"
"    border-bottom-left-radius: 30px;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-family: \"Roboto\";\n"
"    font-weight: 900;  /* Semibold */\n"
"    font-size: 16px;\n"
"    color: #333333;\n"
"    position: relative;\n"
"}\n"
"\n"
"\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    border-top-right-radius: 30px;\n"
"    border-bottom-right-radius: 30px;\n"
"    padding: 30px;\n"
"    border: none;\n"
"    font-family: \"Roboto\";\n"
"    font-weight: 900;  /* Semibold */\n"
"    font-size: 16px;\n"
"    color: #333333;\n"

"    position: relative;\n"
"}\n"
"\n"
"\n"
"")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("imagenes/rojo.png"))
        self.label_17.setScaledContents(False)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    border-top-left-radius: 30px;\n"
"    border-bottom-left-radius: 30px;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-family: \"Roboto\";\n"
"    font-weight: 900;  /* Semibold */\n"
"    font-size: 16px;\n"
"    color: #333333;\n"

"    position: relative;\n"
"}\n"
"\n"
"\n"
"")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_12.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    border-top-right-radius: 30px;\n"
"    border-bottom-right-radius: 30px;\n"
"    padding: 30px;\n"
"    border: none;\n"
"    font-family: \"Roboto\";\n"
"    font-weight: 900;  /* Semibold */\n"
"    font-size: 16px;\n"
"    color: #333333;\n"

"    position: relative;\n"
"}\n"
"\n"
"\n"
"")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("imagenes/amarillo.png"))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_12.addWidget(self.label_21)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    border-top-left-radius: 30px;\n"
"    border-bottom-left-radius: 30px;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font-family: \"Roboto\";\n"
"    font-weight: 900;  /* Semibold */\n"
"    font-size: 16px;\n"
"    color: #333333;\n"

"    position: relative;\n"
"}\n"
"\n"
"\n"
"")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_13.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    border-top-right-radius: 30px;\n"
"    border-bottom-right-radius: 30px;\n"
"    padding: 30px;\n"
"    border: none;\n"
"    font-family: \"Roboto\";\n"
"    font-weight: 900;  /* Semibold */\n"
"    font-size: 16px;\n"
"    color: #333333;\n"

"    position: relative;\n"
"}\n"
"\n"
"\n"
"")
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("imagenes/verde.png"))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_13.addWidget(self.label_23)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.Cliente.setText(_translate("MainWindow", "Taller"))
        self.btnNuevoPedido.setText(_translate("MainWindow", "Nuevo Pedido"))
        self.label_16.setText(_translate("MainWindow", "Solicitados"))
        self.label_20.setText(_translate("MainWindow", "En proceso"))
        self.label_22.setText(_translate("MainWindow", "Para entregar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
