# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QFont, QPixmap


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 900)
        MainWindow.setMinimumSize(1400, 900)
        
        # Widget central
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Layout principal
        self.layout_principal = QtWidgets.QHBoxLayout(self.centralwidget)
        self.layout_principal.setContentsMargins(0, 0, 0, 0)
        self.layout_principal.setSpacing(0)
        
        # Panel lateral
        self.sidePanel = QtWidgets.QFrame()
        self.sidePanel.setFixedWidth(300)
        self.sidePanel.setStyleSheet("""
            QFrame {
                background-color: #1e272e;
                border: none;
            }
        """)
        
        self.layout_lateral = QtWidgets.QVBoxLayout(self.sidePanel)
        self.layout_lateral.setContentsMargins(25, 30, 25, 30)
        self.layout_lateral.setSpacing(20)
        
        # Logo o Icono
        self.logo = QtWidgets.QLabel()
        self.logo.setFixedSize(125, 125)
        pixmap = QPixmap("imagenes/logo/logo.png")
        pixmap = pixmap.scaled(125, 125, Qt.KeepAspectRatio, Qt.SmoothTransformation)
        self.logo.setPixmap(pixmap)
        self.logo.setStyleSheet("""
            QLabel {
                border-radius: 40px;
                background-color: transparent;
            }
        """)
        self.layout_lateral.addWidget(self.logo, alignment=Qt.AlignCenter)
        
        # Título
        self.titulo = QtWidgets.QLabel("Taller")
        self.titulo.setFont(QFont("Segoe UI", 28, QFont.Bold))
        self.titulo.setStyleSheet("color: white; margin-bottom: 10px;")
        self.titulo.setAlignment(Qt.AlignCenter)
        self.layout_lateral.addWidget(self.titulo)
        
        # Separador
        self.separador = QtWidgets.QFrame()
        self.separador.setFrameShape(QtWidgets.QFrame.HLine)
        self.separador.setStyleSheet("background-color: #34495e;")
        self.layout_lateral.addWidget(self.separador)
        
        # Botones de navegación
        self.home = QtWidgets.QPushButton("Home")
        self.home.setFont(QFont("Segoe UI", 12))
        self.btnCalendario = QtWidgets.QPushButton("Calendario")
        self.btnCalendario.setFont(QFont("Segoe UI", 12))
        
        for btn in [self.home, self.btnCalendario]:
            btn.setStyleSheet("""
                QPushButton {
                    background-color: #2e86de;
                    color: white;
                    border: none;
                    padding: 12px 20px;
                    border-radius: 8px;
                    text-align: center;
                    font-weight: bold;
                }
                QPushButton:hover {
                    background-color: #54a0ff;
                }
            """)
            self.layout_lateral.addWidget(btn)
        
        self.layout_lateral.addStretch()
        
        # Botón Nuevo Pedido
        self.btnNuevoPedido = QtWidgets.QPushButton("Nuevo Pedido")
        self.btnNuevoPedido.setFont(QFont("Segoe UI", 12, QFont.Bold))
        self.btnNuevoPedido.setStyleSheet("""
            QPushButton {
                background-color: #2ecc71;
                color: white;
                border: none;
                padding: 15px 25px;
                border-radius: 8px;
                text-align: center;
                font-weight: bold;
                margin-top: 20px;
            }
            QPushButton:hover {
                background-color: #27ae60;
            }
        """)
        self.layout_lateral.addWidget(self.btnNuevoPedido)
        
        # Panel principal
        self.pantallaHome = QtWidgets.QFrame(self.centralwidget)
        self.pantallaHome.setStyleSheet("""
            QFrame {
                background-color: #1697D1;
            }
        """)
        
        # Crear los tres contenedores
        self.container_solicitados = QtWidgets.QWidget(self.pantallaHome)
        self.container_proceso = QtWidgets.QWidget(self.pantallaHome)
        self.container_entregar = QtWidgets.QWidget(self.pantallaHome)
        
        # Establecer geometría de los contenedores
        self.container_solicitados.setGeometry(50, 140, 300, 500)
        self.container_proceso.setGeometry(380, 140, 300, 500)
        self.container_entregar.setGeometry(710, 140, 300, 500)
        
        # Títulos de las columnas
        self.label_solicitados = QtWidgets.QLabel("Solicitados", self.pantallaHome)
        self.label_proceso = QtWidgets.QLabel("En Proceso", self.pantallaHome)
        self.label_entregar = QtWidgets.QLabel("Para Entregar", self.pantallaHome)
        
        # Configurar estilo y posición de los títulos
        titulo_style = """
            QLabel {
                color: white;
                font-family: Segoe UI;
                font-size: 20px;
                font-weight: bold;
                background-color: rgba(255, 255, 255, 0.1);
                padding: 10px 20px;
                border-radius: 10px;
            }
        """
        
        for label, x in [(self.label_solicitados, 50), 
                        (self.label_proceso, 380), 
                        (self.label_entregar, 710)]:
            label.setGeometry(x, 80, 300, 45)
            label.setAlignment(Qt.AlignCenter)
            label.setStyleSheet(titulo_style)
        
        # Agregar los paneles al layout principal
        self.layout_principal.addWidget(self.sidePanel)
        self.layout_principal.addWidget(self.pantallaHome)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Taller de Carpintería"))
        self.titulo.setText(_translate("MainWindow", "Taller"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.btnCalendario.setText(_translate("MainWindow", "Calendario"))
        self.btnNuevoPedido.setText(_translate("MainWindow", "Nuevo Pedido"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
