# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pedido-Taller.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QFont


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        MainWindow.setMinimumSize(900, 700)
        MainWindow.setWindowFlags(Qt.Window | Qt.WindowCloseButtonHint | Qt.WindowMinimizeButtonHint)
        
        # Widget central
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("""
            QWidget {
                background-color: #f5f6fa;
            }
        """)
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Layout principal
        self.layout_principal = QtWidgets.QVBoxLayout(self.centralwidget)
        self.layout_principal.setContentsMargins(30, 30, 30, 30)
        self.layout_principal.setSpacing(20)
        
        # Encabezado
        self.header = QtWidgets.QFrame()
        self.header.setStyleSheet("""
            QFrame {
                background-color: white;
                border-radius: 15px;
            }
        """)
        self.header.setMaximumHeight(100)
        
        header_layout = QtWidgets.QHBoxLayout(self.header)
        header_layout.setContentsMargins(20, 0, 20, 0)
        
        # Título del pedido
        self.titulo_pedido = QtWidgets.QLabel("Nuevo Pedido")
        self.titulo_pedido.setFont(QFont("Segoe UI", 24, QFont.Bold))
        self.titulo_pedido.setStyleSheet("color: #2c3e50;")
        header_layout.addWidget(self.titulo_pedido)
        
        # Estado del pedido (si es edición)
        self.estado_pedido = QtWidgets.QComboBox()
        self.estado_pedido.setFont(QFont("Segoe UI", 12))
        self.estado_pedido.addItems(["Solicitado", "En proceso", "Materiales", "Para entregar", "Terminado"])
        self.estado_pedido.setStyleSheet("""
            QComboBox {
                background-color: #f8f9fa;
                border: 2px solid #e9ecef;
                border-radius: 8px;
                padding: 8px 15px;
                min-width: 150px;
            }
            QComboBox::drop-down {
                border: none;
            }
            QComboBox::down-arrow {
                image: url(imagenes/down-arrow.png);
                width: 12px;
                height: 12px;
            }
            QComboBox QAbstractItemView {
                background-color: white;
                selection-background-color: #2e86de;
                selection-color: white;
                border: none;
            }
        """)
        header_layout.addWidget(self.estado_pedido, alignment=Qt.AlignRight)
        
        self.layout_principal.addWidget(self.header)
        
        # Contenido principal
        self.contenido = QtWidgets.QFrame()
        self.contenido.setStyleSheet("""
            QFrame {
                background-color: white;
                border-radius: 15px;
            }
        """)
        
        contenido_layout = QtWidgets.QVBoxLayout(self.contenido)
        contenido_layout.setContentsMargins(30, 30, 30, 30)
        contenido_layout.setSpacing(20)
        
        # Formulario
        form_layout = QtWidgets.QFormLayout()
        form_layout.setSpacing(15)
        form_layout.setLabelAlignment(Qt.AlignRight)
        
        # Estilo para las etiquetas
        label_style = """
            QLabel {
                color: #2c3e50;
                font-family: Segoe UI;
                font-size: 14px;
                font-weight: bold;
            }
        """
        
        # Estilo para los campos de entrada
        input_style = """
            QLineEdit, QDateEdit, QTextEdit {
                background-color: #f8f9fa;
                border: 2px solid #e9ecef;
                border-radius: 8px;
                padding: 8px;
                font-family: Segoe UI;
                font-size: 14px;
                color: #2c3e50;
            }
            QLineEdit:focus, QDateEdit:focus, QTextEdit:focus {
                border-color: #2e86de;
            }
            QDateEdit::drop-down {
                border: none;
            }
            QDateEdit::down-arrow {
                image: url(imagenes/calendar.png);
                width: 12px;
                height: 12px;
            }
        """
        
        # Cliente
        self.label_cliente = QtWidgets.QLabel("Cliente:")
        self.label_cliente.setStyleSheet(label_style)
        self.input_cliente = QtWidgets.QLineEdit()
        self.input_cliente.setStyleSheet(input_style)
        form_layout.addRow(self.label_cliente, self.input_cliente)
        
        # Presupuesto
        self.label_presupuesto = QtWidgets.QLabel("Presupuesto:")
        self.label_presupuesto.setStyleSheet(label_style)
        self.input_presupuesto = QtWidgets.QLineEdit()
        self.input_presupuesto.setStyleSheet(input_style)
        self.input_presupuesto.setPlaceholderText("0")
        form_layout.addRow(self.label_presupuesto, self.input_presupuesto)
        
        # Fecha de medición
        self.label_fecha_medicion = QtWidgets.QLabel("Fecha de medición:")
        self.label_fecha_medicion.setStyleSheet(label_style)
        self.input_fecha_medicion = QtWidgets.QDateEdit()
        self.input_fecha_medicion.setStyleSheet(input_style)
        self.input_fecha_medicion.setCalendarPopup(True)
        form_layout.addRow(self.label_fecha_medicion, self.input_fecha_medicion)
        
        # Fecha de entrega
        self.label_fecha_entrega = QtWidgets.QLabel("Fecha de entrega:")
        self.label_fecha_entrega.setStyleSheet(label_style)
        self.input_fecha_entrega = QtWidgets.QDateEdit()
        self.input_fecha_entrega.setStyleSheet(input_style)
        self.input_fecha_entrega.setCalendarPopup(True)
        form_layout.addRow(self.label_fecha_entrega, self.input_fecha_entrega)
        
        # Fecha de llegada de materiales
        self.label_fecha_materiales = QtWidgets.QLabel("Fecha de materiales:")
        self.label_fecha_materiales.setStyleSheet(label_style)
        self.input_fecha_materiales = QtWidgets.QDateEdit()
        self.input_fecha_materiales.setStyleSheet(input_style)
        self.input_fecha_materiales.setCalendarPopup(True)
        form_layout.addRow(self.label_fecha_materiales, self.input_fecha_materiales)
        
        # Notas
        self.label_notas = QtWidgets.QLabel("Notas:")
        self.label_notas.setStyleSheet(label_style)
        self.input_notas = QtWidgets.QTextEdit()
        self.input_notas.setStyleSheet(input_style)
        self.input_notas.setMinimumHeight(150)
        self.input_notas.setPlaceholderText("Ingrese aquí la descripción y notas adicionales...")
        form_layout.addRow(self.label_notas, self.input_notas)
        
        contenido_layout.addLayout(form_layout)
        
        # Botones de acción
        self.layout_botones = QtWidgets.QHBoxLayout()
        self.layout_botones.setSpacing(15)
        
        # Botón Cancelar
        self.btn_cancelar = QtWidgets.QPushButton("Cancelar")
        self.btn_cancelar.setFont(QFont("Segoe UI", 12))
        self.btn_cancelar.setStyleSheet("""
            QPushButton {
                background-color: #e74c3c;
                color: white;
                border: none;
                padding: 12px 30px;
                border-radius: 8px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #c0392b;
            }
        """)
        self.layout_botones.addWidget(self.btn_cancelar)
        
        # Botón Guardar
        self.btn_guardar = QtWidgets.QPushButton("Guardar")
        self.btn_guardar.setFont(QFont("Segoe UI", 12))
        self.btn_guardar.setStyleSheet("""
            QPushButton {
                background-color: #2ecc71;
                color: white;
                border: none;
                padding: 12px 30px;
                border-radius: 8px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #27ae60;
            }
        """)
        self.layout_botones.addWidget(self.btn_guardar)
        
        contenido_layout.addLayout(self.layout_botones)
        self.layout_principal.addWidget(self.contenido)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pedido"))
        self.titulo_pedido.setText(_translate("MainWindow", "Nuevo Pedido"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
